// Entry point of the verifier bundle (assets/verifier.<hash>.js). See BUILD.md.
import { ALPHABET, cleanSymbols, dammCheckSymbol, dammValid, mulx } from "./crypto/crockford.js";
import {
  ID_LENGTH,
  REVEAL_LENGTH,
  formatId,
  formatRevealKey,
  parseId,
  isValidId,
  parseRevealKey,
  idDigest,
  registryKeyOf,
  shardOf
} from "./crypto/ids.js";
import { NORM_VERSION, normaliseSurname, normaliseEmail, normaliseFactor } from "./crypto/normalise.js";
import { utf8, utf8Decode, b64url, b64urlDecode, hex, hexDecode, concat, equalBytes, wipe, ascii } from "./crypto/bytes.js";
import { sha3_512, taggedSha3, sha3B64 } from "./crypto/sha3.js";
import { argon2id, kdfHeaderProblem, meetsFloor, wasmFellBack, KDF_FLOOR, KDF_CEILING, SEAL_PROFILES } from "./crypto/kdfCore.js";
import { canonicalJson, parseCanonical } from "./crypto/canonical.js";
import {
  unseal,
  decodeRecord,
  openWithFactorKey,
  isSealError,
  kcvOf,
  wrapAad,
  sealAad,
  kdfPassword,
  kdfSalt,
  SEAL_VERSION,
  SEAL_VERSIONS_READABLE,
  SEAL_VERSION_WITH_NAME
} from "./crypto/seal.js";
import {
  parseManifest,
  fileMatches,
  freshness,
  isIsoUtc,
  shardOfRegistryKey,
  SHARD_NAMES,
  manifestDateProblem,
  manifestDigest,
  rollbackVerdict,
  MANIFEST_SCHEMA,
  MAX_EXPIRY_DAYS,
  CLOCK_SKEW_MS
} from "./crypto/manifest.js";
import { fingerprint } from "./crypto/fingerprint.js";
import { verifyManifest, signedMessage, SIGNATURE_ALG } from "./crypto/signingVerify.js";
import { xchacha20poly1305 } from "@noble/ciphers/chacha.js";
const BUNDLE_API = 2;
export {
  ALPHABET,
  BUNDLE_API,
  CLOCK_SKEW_MS,
  ID_LENGTH,
  KDF_CEILING,
  KDF_FLOOR,
  MANIFEST_SCHEMA,
  MAX_EXPIRY_DAYS,
  NORM_VERSION,
  REVEAL_LENGTH,
  SEAL_PROFILES,
  SEAL_VERSION,
  SEAL_VERSIONS_READABLE,
  SEAL_VERSION_WITH_NAME,
  SHARD_NAMES,
  SIGNATURE_ALG,
  argon2id,
  ascii,
  b64url,
  b64urlDecode,
  canonicalJson,
  cleanSymbols,
  concat,
  dammCheckSymbol,
  dammValid,
  decodeRecord,
  equalBytes,
  fileMatches,
  fingerprint,
  formatId,
  formatRevealKey,
  freshness,
  hex,
  hexDecode,
  idDigest,
  isIsoUtc,
  isSealError,
  isValidId,
  kcvOf,
  kdfHeaderProblem,
  kdfPassword,
  kdfSalt,
  manifestDateProblem,
  manifestDigest,
  meetsFloor,
  mulx,
  normaliseEmail,
  normaliseFactor,
  normaliseSurname,
  openWithFactorKey,
  parseCanonical,
  parseId,
  parseManifest,
  parseRevealKey,
  registryKeyOf,
  rollbackVerdict,
  sealAad,
  sha3B64,
  sha3_512,
  shardOf,
  shardOfRegistryKey,
  signedMessage,
  taggedSha3,
  unseal,
  utf8,
  utf8Decode,
  verifyManifest,
  wasmFellBack,
  wipe,
  wrapAad,
  xchacha20poly1305
};
